name: Scheduled Python Scripts

on:
  push:
  schedule:
    - cron: '0 7-18 * * *' # Run every hour from 7 am to 6 pm

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests


    - name: Run download.py
      run: python download.py

    - name: Run csv_to_html.py
      run: python csv_to_html.py

    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code || echo "Changes detected"

    - name: Commit and push changes
      if: steps.check_changes.outputs.stdout == '0'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Auto update"
        git push
        echo "pushed"